language: ruby
services: docker
dist: jammy
arch:
  - amd64
  - arm64
cache:
- bundler
before_install:
  - gem install -v 1.17.3 bundler --no-document
  - bundle _1.17.3_ install
install:
- bundle install
rvm:
- 3.0.2
notifications:
  email:
    recipients:
    - javier.wilson@viamo.io
    on_success: change
    on_failure: always
script:
- bundle exec rake quick
- gem build sensu-plugins-twilio.gemspec
- gem install sensu-plugins-twilio-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
  provider: script
  script:  bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-twilio
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    tags: true
    all_branches: true
    rvm: 3.0.2
